### ISSUE TITLE
Cuanto tienes muchos horarios deberia haber un scroll porque con muchos se solapa como en la foto

### ISSUE THREAD

**Issue by ruddypazd** [StaffProUsa/.github#117]
![Image](https://github.com/user-attachments/assets/7bc73333-88ba-49d2-a746-6ed064e3bf01)

**Comment by Licethd** [comment]
Hecho

![Image](https://github.com/user-attachments/assets/e31a4a4b-c8f7-4dff-8f28-83dfbaa1d845)

**Comment by xaviflores21** [comment]
validado!
