### ISSUE TITLE
Cuando soy compañia no puedo editar los datos del usuario

### ISSUE THREAD

**Issue by carlosdaniel95** [StaffProUsa/.github#125]

**Comment by carlosdaniel95** [comment]
![Image](https://github.com/user-attachments/assets/ae9760df-2a5b-4f8f-948b-fb0ba6f184d4)

**Comment by xaviflores21** [comment]
validado! @GVargas93 
![Image](https://github.com/user-attachments/assets/4e428edb-e1c2-42e9-9b2b-84da99300728)
