### ISSUE TITLE
Cuando recibo una invitacion en español y cambio el idioma a ingles, cambia todo menos el titulo de la invitacion

### ISSUE THREAD

**Issue by carlosdaniel95** [StaffProUsa/.github#133]

**Comment by carlosdaniel95** [comment]
![Image](https://github.com/user-attachments/assets/e6b32310-607d-40ea-a459-87aaa74ac842)

**Comment by carlosdaniel95** [comment]
no se pudo resolver porque la informacion ya viene en español desde el servidor

**Comment by xaviflores21** [comment]
validado!
