### ISSUE TITLE
En la tabla no debe invitar al marcar debe haber un boton invitar cuando selecciono varios

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#139]

**Comment by xaviflores21** [comment]
![Image](https://github.com/user-attachments/assets/cd2ede29-0ca9-4019-ac9f-84b9b0aa7329)


en la invitacion no aparece el nombre o empresa de quien te esta ivitando.
colocar, servisoft te esta invitando a trabajar con nosotros (Ingles)
![Image](https://github.com/user-attachments/assets/af8fdbe5-a024-4f8e-9979-a066e9c8a349)

**Comment by Licethd** [comment]
Se acortó el texto del botón:
![Image](https://github.com/user-attachments/assets/f9173b9e-1a5f-4cbe-9ba8-2156e9ccb57f)

Texto invitación corregido
![Image](https://github.com/user-attachments/assets/975b945a-8f24-4399-bd9b-1c3bcc071c66)

**Comment by xaviflores21** [comment]
validado!
