### ISSUE TITLE
Ordenar la lista de booking por horas trabajadas en la posicion

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#143]

**Comment by xaviflores21** [comment]
si bien fue colocado por debajo, que haya una columna donde se vea las hroas trabajadas de cada persona.
![Image](https://github.com/user-attachments/assets/4b9ebf1c-27b8-4e2a-844c-a5e89e699833)

**Comment by Licethd** [comment]
Hrs. Staff: horas trabajadas en la posición
Hrs. Company: horas trabajas en la compañía


Ordenando por horas trabajadas en la posición:
![Image](https://github.com/user-attachments/assets/00a47cec-b25b-471f-99cd-8e139e33e12c)

**Comment by xaviflores21** [comment]
validado!
