### ISSUE TITLE
Hay un problema en el booking al asignar un jefe que no estaba en la tabla cuando agregamos a ruddy no aparecio

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#144]

**Comment by xaviflores21** [comment]
por ordenes de roger, deja como esta

![Image](https://github.com/user-attachments/assets/877c7f29-0699-4365-a402-a686ddec5264)

![Image](https://github.com/user-attachments/assets/8b4b50ae-1919-4c02-8ccb-372740d77eae)
