### ISSUE TITLE
en la seccion administracion - usuarios es dificil seleccionar un rol

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#156]
se tiene que dar bien en la esquina del recuado para poder seleccionar rol
![Image](https://github.com/user-attachments/assets/21ef2b36-29f3-4bf2-ac9b-b4a7fc51ab44)

**Comment by xaviflores21** [comment]
tambien, al dar click en el boton eventos. 
![Image](https://github.com/user-attachments/assets/593d20f2-cdf2-49de-b21c-b89ca0e7d038)

sale error
![Image](https://github.com/user-attachments/assets/523f56d4-65ae-4ab3-9c61-56530e1759af)

**Comment by xaviflores21** [comment]
se valido los check box!
![Image](https://github.com/user-attachments/assets/08964955-3a83-4d95-ac62-5d432905af63)

pero al darle click a evento vuelve a salir error.
![Image](https://github.com/user-attachments/assets/58c6b343-35f7-476d-bf04-34e3a8bc968a)
![Image](https://github.com/user-attachments/assets/f983441e-d1cb-4089-8ee4-8ab77b139484)

**Comment by xaviflores21** [comment]
corregir lo comentado lineas arriba @ruddypazd @rickypazd

**Comment by Licethd** [comment]
Se quito el bloque porque ya no va con el proyecto

![Image](https://github.com/user-attachments/assets/3dc976d3-72e9-4923-af8d-b8559ad46445)

**Comment by xaviflores21** [comment]
validado!
