### ISSUE TITLE
Usuario de Juan Takeshi tiene todos las position pero no aparece en los eventos

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#157]
El usuario juan takeshi tiene estas positin
![Image](https://github.com/user-attachments/assets/28645ad1-5153-4774-bac8-e6963a16a178)

pero al entrar al evento
![Image](https://github.com/user-attachments/assets/b358a764-2b33-425c-b34d-90e363e09ab1)

no aparece por ningun lado
![Image](https://github.com/user-attachments/assets/0125294e-3332-4ea5-b213-4c5378817e3f)

**Comment by carlosdaniel95** [comment]
EL encargado de la empresa debe aprobar al usuario para que pueda trabajar en la empresa.

![Image](https://github.com/user-attachments/assets/4b9d6993-2264-46eb-86ce-873081a622e3)

**Comment by xaviflores21** [comment]
@GVargas93 en table user hay que habilitar para que aparezca.
![image](https://github.com/user-attachments/assets/c3ca3834-f716-4f04-bab1-e05fd413fd5c)


validado!
