### ISSUE TITLE
Al recibir la invitación debería mostrarme toda información que metió en el paso a paso

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#50]
![Image](https://github.com/user-attachments/assets/807cffcc-199a-4e6d-be5f-92fd0a8b73d3)

**Comment by xaviflores21** [comment]
al compartir el evento y aceptar la invitacion aparece la siguiente ventana

![Image](https://github.com/user-attachments/assets/6cbd404d-7316-4445-bdc9-3059b10736d2)

selecciono el trabajo pero no me aparece la descripcion del trabajo para el cual estoy postulando.
![Image](https://github.com/user-attachments/assets/3c7c88f7-6d03-42fd-871d-200872ada52b)

**Comment by xaviflores21** [comment]
validado
