### ISSUE TITLE
Verificar que todos los formularios también estén también en inglés, revisar todo el contenido 

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#51]

**Comment by Licethd** [comment]
no pude editar el idioma de imputs y botones donde se use la estructura para administración

**Comment by xaviflores21** [comment]
sigue apareciendo campos y textos en espanol

![Image](https://github.com/user-attachments/assets/c430f212-a0d2-47c4-a228-e7674cadf3d4)

**Comment by xaviflores21** [comment]
validado!
