### ISSUE TITLE
Las fechas que sean formato MES DÍA y AÑO

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#53]

**Comment by xaviflores21** [comment]
la fecha aun no esta mes dia anho.
y validar la hora, uno borra todo y no da el formato correcto

![Image](https://github.com/user-attachments/assets/96f1f1a6-4d30-436b-b7bb-d7e6b3febf55)

**Comment by xaviflores21** [comment]
validado!
![Image](https://github.com/user-attachments/assets/8c88365d-99a3-4c23-a502-ec8d2399518c)
