### ISSUE TITLE
Tipo staff default

### ISSUE THREAD

**Issue by ruddypazd** [StaffProUsa/.github#55]
Al crear las compañías deben tenes por defaul las siguientes: Supervisor Capitan Bartender Full Bar Bartender Server VIP Server Runner Driver Cook Prep Cook Utility Cashier con la opción de agregar o eliminar

**Comment by ruddypazd** [comment]
Que se pueda seleccionar tipo staff default (De la app) para todas las companys, asi una vez se configuran los default aparecen.

**Comment by xaviflores21** [comment]
validado!
