### ISSUE TITLE
En el armado de staff dar la opción de ENVIAR el evento a las personas ya seleccionadas o boton GUARDAR, SEND o DONE para que cierre esa ventana (creo que desconoce que al elegir al staff automáticamente le llegará la invitación en el perfil personal del usuario elegido)

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#58]

**Comment by xaviflores21** [comment]
no me llego ninguna verificacion que fui aceptado para el evento una vez me agragaron y di guardar

![Image](https://github.com/user-attachments/assets/93bd9a39-318d-449f-b09b-b492b56069e6)

queda en esta ventana

![Image](https://github.com/user-attachments/assets/d150633b-3281-4d7e-bb54-aeb0b26533ff)

**Comment by xaviflores21** [comment]
validado con el boton check
