### ISSUE TITLE
Al crear usuario  debería solicitar más detalles: Al momento de que un usuario crea su perfil tiene que tener mil preguntas para que se filtre mejor a la hora del booking

### ISSUE THREAD

**Issue by ruddypazd** [StaffProUsa/.github#59]

**Comment by Licethd** [comment]
Necesitamos nos proporcionen los detalles, información adicional a pedir del usuario.
Actualmente pedimos la siguientes datos:
![Image](https://github.com/user-attachments/assets/fe6be9ec-6c4f-416a-b676-bd6737bc17a0)

**Comment by xaviflores21** [comment]
segun el requerimiento en verde, deberia mostrarme solo los bartender disponibles
pero aparece todos los servicios

![Image](https://github.com/user-attachments/assets/480a2d15-cdc7-4ccc-99c3-f6091d3efccb)

**Comment by xaviflores21** [comment]
validado!
