### ISSUE TITLE
Es un poco complicado manejar el Zoom in y zoom out, si se puede mejorar. adicional, que guarde el nombre de la ubicacion cuando se esta navegando. FUNCIONE COMO TAPEKE

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#63]
se creo una nueva compania y al crear al cliente o estadio no carga la ubicacion

![Image](https://github.com/user-attachments/assets/acc23d23-9b4e-45b4-9041-e9d2047a2483)

deberia dar un click y cargar automatico sin necesidad de colocar la ubicacion manual.

**Comment by Licethd** [comment]
El usuario debe escribir una descripción textual de la dirección, ya se corrigió:
![Image](https://github.com/user-attachments/assets/6f6ba617-5822-4c96-a0b3-b2dd66ebdcf6)

**Comment by xaviflores21** [comment]
Aparte de escribir en el espacio en Rojo, pense que ellos seleccionaban en el mapa el punto exacto.
Se quedo asi con Roger al Final?

**Comment by Licethd** [comment]
Por debajo se están guardando coordenadas

![Image](https://github.com/user-attachments/assets/20fa142f-64fe-416b-9e0f-5b27e3770ce5)

**Comment by xaviflores21** [comment]
Es un poco complicado manejar el Zoom in y zoom out, si se puede mejorar mejor.
adicional, que guarde el nombre de la ubicacion cuando se esta navegando.

**Comment by xaviflores21** [comment]
validao!
