### ISSUE TITLE
Al editar un usuario X, no aparece staff o tipo (bartender, cocinero, albanil)

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#64]
aparece todos los campos menos el staff

![Image](https://github.com/user-attachments/assets/a4908721-2a58-4dbf-928a-b262cfd27c50)

**Comment by xaviflores21** [comment]
en este issue #65 quiere editar su propio perfil pero no le aparece los staff que el sabe hacer (cicinar, bar, etc.)

**Comment by Licethd** [comment]
Está en:
![Image](https://github.com/user-attachments/assets/c6b31961-0cd5-4664-a18c-dc8a34cd6f90)
![Image](https://github.com/user-attachments/assets/11baacf0-b514-4a53-bdfd-3ea1297e6625)


y también se adicionó al editar perfil:
![Image](https://github.com/user-attachments/assets/07692c40-a844-42f2-a3d3-5c435ce95060)

**Comment by xaviflores21** [comment]
buenisimo!!
validado!
