### ISSUE TITLE
Cuando se crea un nueva empresa, tiene que aparecer en el staff typo una lita por defecto

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#70]
![Image](https://github.com/user-attachments/assets/363f1df2-cda7-4702-b20d-51ed6f49682f)
![Image](https://github.com/user-attachments/assets/dc8c5cd6-45e8-4dcd-a735-59a7000d09bf)

tiene que aparecer esta lista
![Image](https://github.com/user-attachments/assets/7e12b42b-6c98-4795-8af0-80eba3ee9ffd)

Lista:
Supervisor
Capitan 
Bartender Full Bar
Bartender
Server VIP
Server
Runner 
Driver 
Cook 
Prep Cook
Utility 
Cashier

**Comment by Licethd** [comment]
@ruddypazd

**Comment by xaviflores21** [comment]
validado!
