### ISSUE TITLE
Fotmato Dark (intefaz) cambiar a un color mas light

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#71]
Cambiar a un color mas suave la interfaz de Staff.
hay ventanas donde los colores rojo, azul opaca con el color negro

![Image](https://github.com/user-attachments/assets/625a3135-4aba-48ad-ba37-cc1260ddb614)

**Comment by Licethd** [comment]
ya tenemos un tema con tonos claros:
![Image](https://github.com/user-attachments/assets/8e377b04-427c-4896-8f7f-bcd793f4af0a)
![Image](https://github.com/user-attachments/assets/2c217532-fd8c-4a1b-9426-31588124eb1e)

para cambiar de tema en menu PROFILE:
![Image](https://github.com/user-attachments/assets/6af2687e-5325-4bca-84ac-95b8d5d51106)

**Comment by xaviflores21** [comment]
El diseno no es agrado del Cliente.
busquemos un diseno mas presentable, o solicitar que nos pasen los colores y disenos.

**Comment by xaviflores21** [comment]
este diseno mejorar para que se distingan los colores de las letras

![Image](https://github.com/user-attachments/assets/60404a18-0c25-4712-b625-74a482cc0faf)

**Comment by Licethd** [comment]
![Image](https://github.com/user-attachments/assets/e7104809-e712-4663-96f2-3a87d661e289)

**Comment by xaviflores21** [comment]
validado!
