### ISSUE TITLE
Cuando uno pone la hora tiene que tener un drop down para poner la hora predeterminada

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#72]

**Comment by Licethd** [comment]
es un input simple que valida formato de hora al introducir valores

**Comment by xaviflores21** [comment]
un ejemplo de lo que se pide
![Image](https://github.com/user-attachments/assets/c0647397-084f-42bb-8555-49f1fbcc98e8)

**Comment by xaviflores21** [comment]
validado!
![Image](https://github.com/user-attachments/assets/743b19c6-f802-4229-b4d4-19f80a7ae654)
