### ISSUE TITLE
Darle funcionalidad a la lista de trabajos en curso dentro de ASISTENCIA

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#73]

**Comment by Licethd** [comment]
![Image](https://github.com/user-attachments/assets/5d3c7766-d69b-4c84-946d-83ec50de20ff)

**Comment by xaviflores21** [comment]
validado!
![Image](https://github.com/user-attachments/assets/30f535cb-3072-443a-9de7-9452c5d8dd15)
