### ISSUE TITLE
Poner solo los staff tipo que el dijo

### ISSUE THREAD

**Issue by ruddypazd** [StaffProUsa/.github#76]

**Comment by ruddypazd** [comment]
![Image](https://github.com/user-attachments/assets/20064f99-4cb5-4981-bea3-215863055d8c)

**Comment by ruddypazd** [comment]
![Image](https://github.com/user-attachments/assets/6eeb41af-28c7-40b8-a8a0-e7b18084a4f1)

**Comment by xaviflores21** [comment]
validado!
