### ISSUE TITLE
Al crear un nuevo evento, la fecha no deberia modificarse, solo se tiene que editar la hora para cada recluta.

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#78]
cuando creas un nuevo evento con la fecha del evento como tal.

la fecha que aparece tiene que aparecer como informacion de acuerdo al evento creado con la fecha creada
![Image](https://github.com/user-attachments/assets/0d351c53-01f3-46cf-b2eb-a2553c729186)

![Image](https://github.com/user-attachments/assets/2153be76-8b2c-4939-bf38-5dcddc072a65)

y cuando se quiere editar un evento, la fecha no deberia modificarse, solo la hora.
![Image](https://github.com/user-attachments/assets/9d4be670-e8d4-461f-b67b-b1c53aa837d0)

**Comment by Licethd** [comment]
![Image](https://github.com/user-attachments/assets/9c35e6d3-4164-4fc0-8bbd-0c90bae882d5)

**Comment by xaviflores21** [comment]
validado!
