### ISSUE TITLE
Cambiar list cliente por list client

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#83]
![Image](https://github.com/user-attachments/assets/0f05c58c-fdb1-4c11-acb1-a25c05a2d850)

![Image](https://github.com/user-attachments/assets/cc3e6d2f-6477-450d-b5af-faa7cee6753e)

**Comment by Licethd** [comment]
![Image](https://github.com/user-attachments/assets/ff315ec8-9f8a-447c-9186-326e07088ab4)

**Comment by xaviflores21** [comment]
validado!
