### ISSUE TITLE
El edit skill en edit profile ir arriba de confirmar

### ISSUE THREAD

**Issue by xaviflores21** [StaffProUsa/.github#84]
![Image](https://github.com/user-attachments/assets/c88da9a1-89a9-40c4-8f9a-75e0d0afa5ef)

**Comment by Licethd** [comment]
![Image](https://github.com/user-attachments/assets/e97efba0-e83e-46b4-b507-6cc0ce8e5afa)

**Comment by xaviflores21** [comment]
validado!
