### ISSUE TITLE
Alerta en la tabloa que no puedes iunvitar a usuarios en fechas pasadas

### ISSUE THREAD

**Issue by Licethd** [StaffProUsa/.github#87]

**Comment by Licethd** [comment]
![Image](https://github.com/user-attachments/assets/555a6be7-1b00-427b-8653-a5af320414ae)
![Image](https://github.com/user-attachments/assets/d3d6f8c9-8b20-4bb9-9217-f7b347aeac59)

**Comment by xaviflores21** [comment]
validado!
