### ISSUE TITLE
datos para registrar usuario

### ISSUE THREAD

**Issue by rickypazd** [StaffProUsa/.github#89]

**Comment by rickypazd** [comment]
#1
 
- Foto (FALTA)
- Nombres
- Apellidos
- Telefono
- Email
- Nivel de ingles
- Esta autorizado para trabajar en estados unidos?
- Dirección  (FALTA)

 #2

- Posiciones

**Comment by Licethd** [comment]
Usuarios (mensaje de Roger)

Nombre 
Apellidos
Fecha de nacimiento 
Estado marital 
Teléfono
Email 
Dirección de mi casa 
Nivel de inglés
Idiomas que hablo 
Posiciones de trabajo 
Si estoy legal para trabajar en los estados unidos

**Comment by xaviflores21** [comment]
validado!
![Image](https://github.com/user-attachments/assets/29e8cca7-afce-4f27-9757-5d10f1228bd1)
